# Generated by Django 2.0.7 on 2018-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilleEtUneNuitsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_door_garden', models.IntegerField(default=-1)),
                ('pin_door_garden_duration', models.IntegerField(default=10)),
                ('pin_door_cave', models.IntegerField(default=-1)),
                ('pin_door_cave_duration', models.IntegerField(default=10)),
                ('pin_door_lamp', models.IntegerField(default=-1)),
                ('pin_door_lamp_duration', models.IntegerField(default=10)),
            ],
        ),
    ]
