# Generated by Django 2.0.7 on 2018-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mille_et_une_nuits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milleetunenuitssettings',
            name='video_path',
            field=models.CharField(default='/opt/vc/src/hello_pi/hello_video/test.h264', max_length=255),
        ),
    ]
