# Generated by Django 2.0.7 on 2018-07-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mille_et_une_nuits', '0002_milleetunenuitssettings_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='milleetunenuitssettings',
            name='video_player',
            field=models.CharField(default='omxplayer', max_length=255),
        ),
    ]
