# Generated by Django 2.0.7 on 2018-10-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='uploads/images')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MultimediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('audio_out', models.CharField(choices=[('hdmi', 'HDMI'), ('local', 'Headphone'), ('both', 'Both')], default='both', max_length=6)),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='video', max_length=6)),
                ('path', models.FileField(upload_to='uploads/media')),
                ('status', models.CharField(default='stopped', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
