# Generated by Django 2.0.7 on 2018-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_type', models.CharField(choices=[('challenge', 'Challenge'), ('door', 'Door'), ('map', 'Map'), ('room', 'Room')], default='room', max_length=255)),
                ('image_path', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_player_name', models.CharField(max_length=255)),
                ('video_player_path', models.CharField(max_length=255)),
            ],
        ),
    ]
