# Generated by Django 2.0.7 on 2018-10-01 10:20

from django.db import migrations, models
import multimedia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('audio_name', models.CharField(max_length=255, unique=True)),
                ('audio_path', models.FileField(upload_to='uploads/audios')),
            ],
            options={
                'ordering': ['audio_name'],
            },
            bases=(multimedia.models.PlayerControlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, unique=True)),
                ('image_path', models.ImageField(upload_to='uploads/images')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('video_path', models.FileField(upload_to='uploads/videos')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(multimedia.models.PlayerControlMixin, models.Model),
        ),
    ]
