# Generated by Django 2.0.7 on 2018-08-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('ip_address', models.CharField(max_length=16)),
                ('code_template', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='EscapeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('video_path', models.CharField(max_length=255)),
                ('map_image_path', models.ImageField(upload_to='uploads')),
                ('sas_door_pin', models.IntegerField(default=7)),
                ('sas_door_locked', models.BooleanField(default=True, editable=False)),
                ('sas_door_image_path', models.ImageField(default='', upload_to='uploads')),
                ('corridor_door_pin', models.IntegerField(default=9)),
                ('corridor_door_locked', models.BooleanField(default=True, editable=False)),
                ('corridor_door_image_path', models.ImageField(default='', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='EscapeGameChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('solved', models.BooleanField(default=False)),
                ('challenge_image_path', models.ImageField(default='', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='EscapeGameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('map_image_path', models.ImageField(default='', upload_to='uploads')),
                ('door_pin', models.IntegerField(default=5)),
                ('door_locked', models.BooleanField(default=True, editable=False)),
                ('door_image_path', models.ImageField(default='', upload_to='uploads')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGame')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_player', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='escapegamechallenge',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGameRoom'),
        ),
    ]
