# Generated by Django 2.0.7 on 2018-08-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapegame',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
