# Generated by Django 2.0.7 on 2018-08-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0002_escapegame_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_player', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='escapegame',
            name='door_pin',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='escapegame',
            name='door_pin_opened',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='escapegameroom',
            name='door_pin_opened',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='escapegameroom',
            name='door_pin',
            field=models.IntegerField(default=5),
        ),
    ]
