# Generated by Django 2.0.7 on 2018-09-01 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoSketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch_name', models.CharField(max_length=255)),
                ('sketch_path', models.FileField(upload_to='uploads/sketches')),
                ('sketch_code', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Arduino Sketches',
                'verbose_name': 'Arduino Sketch',
            },
        ),
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=32)),
                ('port', models.IntegerField(default=80)),
            ],
            options={
                'verbose_name_plural': 'Raspberry Pis',
                'verbose_name': 'Raspberry Pi',
            },
        ),
        migrations.CreateModel(
            name='RemoteChallengePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_callback_validate', models.URLField(max_length=255)),
                ('url_callback_reset', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteDoorPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_callback_lock', models.URLField(max_length=255)),
                ('url_callback_unlock', models.URLField(max_length=255)),
                ('raspberrypi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.RaspberryPi')),
            ],
        ),
    ]
