# Generated by Django 2.0.7 on 2018-09-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escapegame', '0001_initial'),
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorgpio',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGame'),
        ),
        migrations.AddField(
            model_name='doorgpio',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGameRoom'),
        ),
        migrations.AddField(
            model_name='challengegpio',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGameChallenge'),
        ),
        migrations.AddField(
            model_name='cubegpio',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGame'),
        ),
    ]
