# Generated by Django 2.0.7 on 2018-09-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controllers', '0001_initial'),
        ('escapegame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorgpio',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGame'),
        ),
    ]
