# Generated by Django 2.0.7 on 2018-08-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controllers', '0001_initial'),
        ('escapegame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedoorpin',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGameRoom'),
        ),
        migrations.AddField(
            model_name='remotechallengepin',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.EscapeGameChallenge'),
        ),
        migrations.AddField(
            model_name='remotechallengepin',
            name='raspberrypi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.RaspberryPi'),
        ),
    ]
