# Generated by Django 2.0.7 on 2018-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_auto_20180910_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
